---
title: "compare pairs"
author: "Davmes Tan"
date: "23/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}

packages = c('raster', 'sf',
             'clock', 'tidyverse', 
             'tmap', 'rgdal',
             'dplyr', 'ggplot2',
             'ggiraph', 'DT',
             'plotly', 'crosstalk',
             'forcats', 'scales',
             'arules', 'gtable',
             'grid', 'gridExtra',
             'chron', 'lubridate',
             'kableExtra', 'hms',
             'sp')

for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)

}

rm(p, packages)

```

```{r data_prep_1, include=FALSE}

cc_data <- read_csv("data/cc_data.csv")
loyalty_data <- read_csv("data/loyalty_data.csv")
employee_data <- read_csv("data/car-assignments.csv")

#convert timestamp from character into date/time format
cc_data$timestamp <- date_time_parse(cc_data$timestamp,
                                     zone = "",
                                     format = "%m/%d/%Y %H:%M")

#convert timestamp from character into date/time format
loyalty_data$timestamp <- date_time_parse(loyalty_data$timestamp,
                                     zone = "",
                                     format = "%m/%d/%Y")

#Amend string text for Katrina's Cafe
cc_data <- cc_data %>%
  mutate(location = str_replace_all(location,
                                    pattern = "Katerin.+",
                                    replacement = "Katrina\x27s Caf\xe9"))


loyalty_data <- loyalty_data %>%
  mutate(location = str_replace_all(location,
                                    pattern = "Katerin.+",
                                    replacement = "Katrina\x27s Caf\xe9"))



```

```{r Initiating map, include=FALSE}

#Preparing the map
bgmap <- raster("data/Geospatial/MC2-tourist.tif")


Abila_st <- st_read(dsn = "data/Geospatial", 
                    layer = 'Abila')

gps <- read_csv("data/gps.csv")

gps$Timestamp <- date_time_parse(gps$Timestamp,
                                 zone = "",
                                 format = "%m/%d/%Y %H:%M:%S")

##convert
  gps_sf <- st_as_sf(gps,
                     coords = c("long", "lat"),
                     crs = 4326)

##string to gps path
  gps_path <- gps_sf %>%
    group_by(id) %>%
    summarize(m = mean(Timestamp),
              do_union = FALSE) %>%
    st_cast("LINESTRING")
  
#Discover top locations recorded
locations_gps <- gps 

#Discard the 5th decimal place and have an accuracy of 11.1m
locations_gps$lat <- round(locations_gps$lat, digits = 4)
locations_gps$long <- round(locations_gps$long, digits = 4)
  
```

```{r All POIs, include=FALSE}

records_POI <- locations_gps %>%
  mutate(datestamp = as.Date(Timestamp + 60*60*8)) %>%
  group_by(id) %>%
  mutate(stop = Timestamp - lag(Timestamp)) %>%
  mutate(parked = ifelse(stop >60*3, TRUE,FALSE)) %>%
  mutate(lat111 = trunc(lat*1000)/1000,
         long111 = trunc(long*1000)/1000) %>%
  ungroup() %>%
  filter(parked == TRUE) %>%
  group_by(id, datestamp) %>%
  add_count(id, datestamp, name = "visitcount") %>%
  ungroup() %>%
  rename(timestamp = Timestamp)
records_POI <- records_POI[c(1,5,2,3,4,8,9,6,7,10)]

d_records_POI <- records_POI %>%
  distinct(lat,long, .keep_all = TRUE)

d_POI_tif_sf <- st_as_sf(d_records_POI, 
                   coords = c("long", "lat"), 
                   crs = 4326) %>%
  st_cast("POINT") #%>%

tmBase <- tm_shape(bgmap) +
  tm_rgb(bgmap, r = 1, g = 2, b = 3,
         alpha = 0.5,
         saturation = 1,
         interpolate = TRUE,
         max.value = 255)

tmrd_records_POI <- tmBase +
  tm_shape(d_POI_tif_sf) + 
  tm_dots(size = 0.3,
          alpha = 1,
          col = "black")

```

```{r match txn with gps}

getTxn <- function(x){
  df.x <- cc_data %>%
  mutate(datestamp = as.Date(timestamp + 60*60*8)) %>%
  filter(datestamp == x) %>%
  group_by(last4ccnum) %>%
  add_count(last4ccnum, name = "count") %>%
  ungroup()
  
  df.x$count <- df.x$count + 2
  
  return(df.x)
}

getGPS <- function(x) {
  
  records_POI %>%
  filter(datestamp == x)

}

joinTxnGPS <- function(x,y) {
  
  x <- x %>%
    select("last4ccnum", "count") %>%
    group_by(last4ccnum, count) %>%
    distinct(last4ccnum, count) %>%
    ungroup()
  y <- y %>%
    select("id", "visitcount") %>%
    group_by(id, visitcount) %>%
    distinct(id, visitcount) %>%
    ungroup()
  
  z <- inner_join(x, y,
                  by = c("count" = "visitcount"))
  
}

combinedpairs <- setNames(data.frame(matrix(ncol = 3, nrow = 0)), c("last4ccnum", "count", "id"))

for(i in 6:19){
  
  txnDate <- paste("2014-01-", i, sep = "")
  
  x.txn <- getTxn(txnDate)
  y.Gps <- getGPS(txnDate)
  z.join <- joinTxnGPS(x,y)
  
  combinedpairs <-rbind(combinedpairs, z.join)
  
}

match_pairs <- combinedpairs %>%
  distinct(last4ccnum, id, .keep_all = TRUE)


```